version: '3'

services:
  postgres:
    container_name: postgres
    image: 'postgres:14-alpine'
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ventdb
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "50m"

volumes:
  postgres_data:
